// GitHub v0.1.0
// This theme is generated by a converter script.
// Original Textmate Theme: GitHub by Martin Kühl. A theme based on the GitHub code stylesheet.
// The conversion is still incomplete. Any suggestions or any problems,
// please contact me at yanyu [at] cyblogic [dot] com.
// More at http://github.com/yanyu/github.tmtheme

PacuEditorFG = '#000000';
PacuEditorBG = '#F8F8FF';
PacuEditorCursor = '#000';
PacuEditorSelection = '#FFFFAA';
PacuEditorMatch = '#FF6';
PacuEditorBracketMatch = PacuEditorMatch;
PacuEditorCurrentLine = '#FFFEEB';
PacuComment = '#999988';
PacuBlockComment = '#999988';
PacuHtmlComment = '#999988';
PacuString = '#DD1144';
PacuStringLiteral = '#DD1144';
PacuRegularExpression = '#009926';
PacuInterpolation = '#DD1144';
PacuRubyInterpolation = '#DD1144';
PacuChar = '#DD1144';
PacuDocument = '#DD1144';
PacuNumber = '#009999';
PacuRubyNumber = '#009999';
PacuInteger = '#009999';
PacuFloat = '#009999';
PacuKeyword = {color: '#000000', bold: true};
PacuJavascriptKeyword = {color: '#000000', bold: true};
PacuObjcKeyword = {color: '#000000', bold: true};
PacuPreprocessing = '#000000';
PacuBuiltinConstant = {color: '#000000', bold: true};
PacuEscape = '#000000';
PacuBlock = '#000000';
PacuSymbol = '#990073';
PacuVariable = '#000000';
PacuRubyVariable = '#000000';
PacuPunctuator = '#666666';
PacuOperator = {color: '#000000', bold: true};
PacuArrayBracket = '#000000';
PacuBackslashSequence = '#000000';
PacuTag = '#000000';
PacuTagName = '#000080';
PacuTagOpen = '#000000';
PacuTagClose = '#000000';
PacuTagOther = '#000000';
PacuTagAttribute = '#008080';
PacuTagValue = '#000000';
PacuErbTag = '#000000';

charcoal.themes["GitHub"] =
{
	displayName: "GitHub",

	layers: {
		"ruby": {
			"Comment": PacuComment,
			"BlockComment": PacuBlockComment,
			"Keyword": PacuKeyword,
			"DeclarationKeyword": PacuKeyword,
			"Builtin": PacuBuiltinConstant,
			"String": PacuString,
			"EscapeSequence": PacuEscape,
			"Interpolation": PacuInterpolation,
			"Block": PacuBlock,
			"Document": PacuDocument,
			"Integer": PacuInteger,
			"Float": PacuFloat,
			"Symbol": PacuSymbol,
			"ObjectName": PacuRubyVariable,
			"Operator": PacuOperator,
			"OpeningBracket": PacuArrayBracket,
			"ClosingBracket": PacuArrayBracket
		},
		"python": {
			"Comment": PacuComment,
			"String": PacuString,
			"Keyword": PacuKeyword,
			"Identifier": PacuKeyword,
			"Operator": PacuOperator,
			"Float": PacuFloat,
			"Integer": PacuInteger
		},
		"javascript": {
			"Comment": PacuComment,
			"Keyword": PacuJavascriptKeyword,
			"ReservedWord": PacuJavascriptKeyword,
			"FutureReservedWord": PacuJavascriptKeyword,
			"Identifier": PacuOperator,
			"DecimalLiteral": PacuNumber,
			"HexIntegerLiteral": PacuNumber,
			"StringLiteral": PacuStringLiteral,
			"EscapeSequence": PacuEscape,
			"BackslashSequence": PacuBackslashSequence,
			"RegularExpressionLiteral": PacuRegularExpression,
			"Punctuator" : PacuPunctuator,
			"DivPunctuator" : PacuPunctuator
		},
		"xml": {
			"Comment": PacuHtmlComment,
			"TagName": PacuTagName,
			"TagOpen": PacuTagOpen,
			"TagClose": PacuTagClose,
			"AttributeName": PacuTagAttribute,
			"AttributeValue": PacuTagValue,
			"ScriptTagName": PacuTagOther
		},
		"erb": {
			"ErbComment": PacuComment,
			"ErbStart": PacuErbTag,
			"ErbEnd": PacuErbTag
		},
		"cxx": {
			"BlockComment": PacuBlockComment,
			"LineComment": PacuComment,
			"PreprocessingComment": PacuComment,
			"Preprocessing": PacuPreprocessing,
			"EscapedChar": PacuEscape,
			"String": PacuString,
			"ObjcEscapedChar": PacuEscape,
			"ObjcString": PacuString,
			"Keyword": PacuKeyword,
			"TypeKeyword": PacuKeyword,
			"QtKeyword": PacuKeyword,
			"ObjcKeyword": PacuObjcKeyword,
			"Integer": PacuInteger,
			"Float": PacuFloat,
			"Char": PacuChar,
			"Punctuator" : PacuPunctuator
		},
		"bash": {
			"Comment": PacuComment,
			"SingleQuoted": PacuString,
			"DoubleQuoted": PacuString,
			"Document": PacuDocument,
			"EscapedChar": PacuEscape,
			"Expansion": PacuInterpolation,
			"Operator": PacuOperator,
			"Builtin": PacuBuiltinConstant,
			"Reserved": PacuKeyword,
			"Integer": PacuInteger
		}
	},
	
	editor: {
		foreground: PacuEditorFG,
		background: PacuEditorBG,
		cursor: PacuEditorCursor,
		lineNumbers: "#808080",
		lineNumbersBright: "#000",
		lineNumbersBackground: "#F2F2F2",
		lineNumbersBackgroundBright: "#E5E5E5",
		selection: PacuEditorSelection,
		match: PacuEditorMatch,
		bracketMatch: PacuEditorBracketMatch,
		currentLine: PacuEditorCurrentLine
	}
};
